---
spring:
  jpa:
#    show-sql: false
  mvc.favicon.enabled: false

jwt:
  clientId: glee-o-meter
  client-secret: secret
  signing-key: 123
  accessTokenValidititySeconds: 100
  refreshTokenValiditySeconds: 1000
